[project]
name = "my-workspace"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13" # recordatorio: puedes establecer la version de python que quieras
dependencies = [
    "ipykernel>=7.2.0",
    "polars>=1.43.2",
]

[tool.uv]
package = true # habilita el modo paquete editable, recomiendo investigar por qué es conveniente tenerlo asi

#[tool.hatch.build.targets.wheel] # luego subo para qué sirve
#packages = ["carpeta1", "carpeta2"]